export const lenses = ["All", "Publish", "Convene", "Teach", "Practice", "Experiment"];

export const projects = [
  {
    code: "PUB-001",
    slug: "teaming-with-ai",
    title: "Teaming with AI",
    shortTitle: "Teaming with AI",
    format: "White paper + community",
    lenses: ["Publish", "Convene", "Experiment"],
    state: "OPEN INQUIRY",
    period: "2023—NOW",
    dek: "A practical investigation into how AI changes roles, trust, collaboration, and decision-making inside teams.",
    question: "What changes when AI becomes a teammate?",
    description: "Teaming with AI offers orientation rather than a finished doctrine: ten insights, exercises for AI integration, and a growing international community exploring the changing nature of teamwork.",
    contribution: "Co-initiator and co-author",
    href: "https://www.teamingwith.ai/",
    sourceLabel: "teamingwith.ai",
    accent: "yellow",
    featured: true,
    takeaways: ["AI changes team dynamics, not only tool choice.", "Roles and decision rights need to be made visible.", "The work stays open so teams can test it in their own context."],
  },
  {
    code: "BK-001",
    slug: "this-is-service-design-doing",
    title: "This is Service Design Doing",
    shortTitle: "Service Design Doing",
    format: "Book",
    lenses: ["Publish", "Practice"],
    state: "IN USE",
    period: "2018",
    dek: "A practitioner’s handbook for applying service design thinking in the real world.",
    question: "How do we move service design from intention into practice?",
    description: "Built with a global community of contributors, the book connects service design principles to the practical work of research, ideation, prototyping, facilitation, and implementation.",
    contribution: "Co-author",
    href: "https://www.thisisservicedesigndoing.com/",
    sourceLabel: "tisdd.com",
    accent: "paper",
    featured: true,
    takeaways: ["Make service design tangible through shared tools.", "Treat prototyping as a way to learn, not merely to validate.", "Build a common language across organizational boundaries."],
  },
  {
    code: "BK-002",
    slug: "this-is-service-design-methods",
    title: "This is Service Design Methods",
    shortTitle: "Service Design Methods",
    format: "Book",
    lenses: ["Publish", "Practice"],
    state: "IN USE",
    period: "2018",
    dek: "A compact companion of methods for research, ideation, prototyping, and facilitation.",
    question: "Which method helps a team make the next useful move?",
    description: "The companion volume turns the method library into a practical reference for real projects, with step-by-step guidance and variations for different contexts.",
    contribution: "Co-author",
    href: "https://www.thisisservicedesigndoing.com/methods",
    sourceLabel: "TiSDD methods",
    accent: "paper",
    featured: false,
    takeaways: ["Choose methods for purpose and context.", "Adapt the format instead of performing a recipe.", "Leave teams with a reusable way of working."],
  },
  {
    code: "EV-001",
    slug: "ai-camp",
    title: "AI Camp",
    shortTitle: "AI Camp",
    format: "Annual conference",
    lenses: ["Convene", "Experiment"],
    state: "RECURRING",
    period: "ANNUAL",
    dek: "An annual gathering for testing how AI changes collaboration, organizations, and the practice of innovation.",
    question: "What can we learn together that none of us can settle alone?",
    description: "AI Camp treats a conference as a working format: shared questions, practical sessions, and a community that compares real experiences instead of staging certainty.",
    contribution: "Initiator and host",
    href: "https://www.teamingwith.ai/",
    sourceLabel: "Teaming with AI",
    accent: "black",
    featured: true,
    takeaways: ["A conference can operate as a collective prototype.", "Unresolved questions belong in the room.", "Participants should leave with something they can try."],
  },
  {
    code: "EV-002",
    slug: "global-service-jam",
    title: "The Global Service Jam",
    shortTitle: "Global Service Jam",
    format: "Global Jam",
    lenses: ["Convene", "Practice"],
    state: "LIVE NETWORK",
    period: "2011—NOW",
    dek: "A volunteer-led global event where people learn service design by making and testing together in 48 hours.",
    question: "How much can strangers make together in one weekend?",
    description: "The Jam began in 2011 and grew into a distributed culture of experimentation. Local hosts create the conditions; Jammers research, prototype, share, and learn through DoingNotTalking.",
    contribution: "Co-initiator and global host",
    href: "https://www.globaljams.org/",
    sourceLabel: "globaljams.org",
    accent: "image",
    image: "/images/global-service-jam-ube-opening.jpg",
    imageAlt: "Participants discussing ideas around workshop tables at the Ube Global Service Jam in Baguio.",
    credit: "Ube Jam / Gabe Mercado and Franz Fontanilla, CC BY",
    featured: true,
    takeaways: ["DoingNotTalking turns a slogan into event architecture.", "A small central structure can enable global local ownership.", "Productive play helps people cross professional boundaries."],
  },
  {
    code: "EV-003",
    slug: "global-sustainability-jam",
    title: "The Global Sustainability Jam",
    shortTitle: "Sustainability Jam",
    format: "Global Jam",
    lenses: ["Convene", "Practice"],
    state: "ARCHIVE / LINEAGE",
    period: "2011—",
    dek: "The sustainability-focused sibling of the Service Jam, connecting global themes with local action.",
    question: "How can a global concern become something locally testable?",
    description: "The format applies the Jam’s distributed, hands-on model to sustainability: global framing, local collaboration, rapid making, and open sharing.",
    contribution: "Co-initiator and global host",
    href: "https://www.globaljams.org/about",
    sourceLabel: "Global Jams history",
    accent: "green",
    featured: false,
    takeaways: ["Scale comes from participation, not central control.", "Local specificity makes global questions actionable.", "Prototype the relationship, not only the object."],
  },
  {
    code: "EV-004",
    slug: "global-ai-jam",
    title: "Global AI Jam",
    shortTitle: "Global AI Jam",
    format: "Upcoming global Jam",
    lenses: ["Convene", "Experiment"],
    state: "IN DEVELOPMENT",
    period: "UPCOMING",
    dek: "A new participatory format for exploring AI through local making, global exchange, and shared evidence.",
    question: "What should a global community prototype about AI together?",
    description: "The Global AI Jam extends the Jam lineage into a field that needs more collective experimentation and fewer detached predictions.",
    contribution: "Initiator",
    href: "https://www.teamingwith.ai/",
    sourceLabel: "Teaming with AI",
    accent: "yellow",
    featured: true,
    takeaways: ["The format is still being shaped.", "Local experiments can expose global patterns.", "Participation must be meaningful, not performative."],
  },
  {
    code: "EDU-001",
    slug: "genai-games-hm",
    title: "GenAI Games — HM.edu",
    shortTitle: "GenAI Games",
    format: "Lecture + learning laboratory",
    lenses: ["Teach", "Experiment"],
    state: "FIELD TEST",
    period: "CURRENT",
    dek: "A playful learning format for understanding generative AI through structured challenges and reflection.",
    question: "What becomes learnable when AI is treated as a game material?",
    description: "GenAI Games uses play to lower the threshold for experimentation while keeping attention on judgment, collaboration, and consequences.",
    contribution: "Lecturer and format designer",
    href: "https://www.hm.edu/",
    sourceLabel: "HM.edu",
    accent: "yellow",
    featured: false,
    takeaways: ["Play makes unfamiliar systems discussable.", "A challenge reveals behavior better than a feature tour.", "Reflection turns activity into learning."],
  },
  {
    code: "EDU-002",
    slug: "service-design-mci",
    title: "Service Design — MCI",
    shortTitle: "Service Design at MCI",
    format: "Lecture + course",
    lenses: ["Teach", "Practice"],
    state: "IN USE",
    period: "CURRENT",
    dek: "Service design taught as a practical, collaborative way of investigating and changing real situations.",
    question: "How do students learn a practice rather than memorize a process?",
    description: "The course connects service design principles with hands-on methods, teamwork, field evidence, and repeated prototyping.",
    contribution: "Lecturer",
    href: "https://www.mci.edu/",
    sourceLabel: "MCI",
    accent: "paper",
    featured: false,
    takeaways: ["Practice is learned through practice.", "Methods need a question and a context.", "The quality of collaboration changes the quality of the result."],
  },
  {
    code: "EDU-003",
    slug: "innovation-leadership-fau",
    title: "Innovation and Leadership — FAU",
    shortTitle: "Innovation + Leadership",
    format: "Lecture + course",
    lenses: ["Teach", "Practice"],
    state: "IN USE",
    period: "CURRENT",
    dek: "A course connecting leadership with experimentation, strategic movement, and the realities of organizational change.",
    question: "How can leadership make responsible experimentation possible?",
    description: "The course frames innovation as a team capability shaped by decisions, culture, and the practical conditions for trying things.",
    contribution: "Lecturer",
    href: "https://www.fau.eu/",
    sourceLabel: "FAU",
    accent: "paper",
    featured: false,
    takeaways: ["Leadership shapes the conditions for experimentation.", "Strategy becomes useful when a team can act on it.", "Learning speed matters more than theatre."],
  },
  {
    code: "TK-001",
    slug: "ai-native-teams-zollhof",
    title: "AI Native Teams — ZOLLHOF Nürnberg",
    shortTitle: "AI Native Teams",
    format: "Talk",
    lenses: ["Teach", "Experiment"],
    state: "PRESENTED",
    period: "CURRENT",
    dek: "A talk about teams designed around the presence of AI rather than retrofitted with another tool.",
    question: "What if the team itself—not the workflow—were redesigned for AI?",
    description: "The talk turns the Teaming with AI inquiry into a concise public proposition about roles, trust, and decision-making.",
    contribution: "Speaker",
    href: "https://www.zollhof.de/",
    sourceLabel: "ZOLLHOF",
    accent: "black",
    featured: false,
    takeaways: ["AI-native is an organizational question.", "Team roles become design material.", "Trust needs observable practices."],
  },
  {
    code: "WS-001",
    slug: "future-of-service-design-ai",
    title: "Future of Service Design × AI",
    shortTitle: "Future of SD × AI",
    format: "Workshop",
    lenses: ["Practice", "Experiment"],
    state: "OPEN FORMAT",
    period: "CURRENT",
    dek: "A participatory workshop for rehearsing how AI may change the discipline, its roles, and its responsibilities.",
    question: "Which parts of service design should change—and which should not?",
    description: "Participants use concrete situations and prototypes to investigate the future of the practice without turning prediction into certainty.",
    contribution: "Workshop designer and facilitator",
    href: "https://www.workplayexperience.com/",
    sourceLabel: "WorkPlayExperience",
    accent: "yellow",
    featured: false,
    takeaways: ["The future is easier to discuss when it can be experienced.", "A discipline changes through practice, not declarations.", "Tensions are more useful than consensus too early."],
  },
  {
    code: "WS-002",
    slug: "prototyping-ai-service-design",
    title: "Prototyping × AI × Service Design",
    shortTitle: "Prototyping × AI × SD",
    format: "Workshop",
    lenses: ["Practice", "Experiment"],
    state: "OPEN FORMAT",
    period: "CURRENT",
    dek: "A hands-on format for using AI to increase the range and speed of service prototyping without losing human judgment.",
    question: "Where does AI genuinely improve the prototype—and where does it obscure the learning?",
    description: "The workshop combines rapid making with deliberate critique, helping teams distinguish output speed from useful evidence.",
    contribution: "Workshop designer and facilitator",
    href: "https://www.workplayexperience.com/",
    sourceLabel: "WorkPlayExperience",
    accent: "yellow",
    featured: false,
    takeaways: ["Faster output is not automatically faster learning.", "Use AI where it expands what can be tested.", "Keep the decision and its consequences visible."],
  },
  {
    code: "PR-001",
    slug: "workplayexperience",
    title: "WorkPlayExperience — Experience the Change",
    shortTitle: "WorkPlayExperience",
    format: "Practice",
    lenses: ["Practice"],
    state: "ONGOING",
    period: "2007—NOW",
    dek: "A service innovation practice helping organizations experience change through strategic prototypes and hands-on collaboration.",
    question: "How can a strategy become something a team can experience before committing to it?",
    description: "WorkPlayExperience works across public and private organizations to change how staff, partners, and customers work together and create new products and services.",
    contribution: "Co-founder and partner",
    href: "https://www.workplayexperience.com/",
    sourceLabel: "workplayexperience.com",
    accent: "black",
    featured: true,
    takeaways: ["Experience the future instead of only describing it.", "Cheap prototypes can move serious strategy.", "Human-centered change is made with the people involved."],
  },
];

export const labNotes = [
  {
    code: "EXP-001",
    title: "Roles before tools",
    state: "OPEN",
    date: "14 JUL 2026",
    lens: "AI + TEAMING",
    text: "A useful AI experiment begins by making roles, decisions, and handoffs visible—not by comparing feature lists.",
    projectSlug: "teaming-with-ai",
  },
  {
    code: "EXP-002",
    title: "Faster output ≠ faster learning",
    state: "FIELD TEST",
    date: "14 JUL 2026",
    lens: "PROTOTYPING",
    text: "Generative speed matters only when a prototype exposes a question the team can observe and act on.",
    projectSlug: "prototyping-ai-service-design",
  },
  {
    code: "FN-001",
    title: "Play is infrastructure",
    state: "IN USE",
    date: "14 JUL 2026",
    lens: "PARTICIPATION",
    text: "In a Jam or classroom, play is not decoration. It makes uncertainty social, lowers the cost of trying, and gives strangers a way to begin.",
    projectSlug: "global-service-jam",
  },
];

export function projectBySlug(slug) {
  return projects.find((project) => project.slug === slug);
}
